id: AA321C2AB
title: Taking the Vows of Sojong
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 02:21:34.819857
  last_modified_at: 2022-03-01 02:21:34.819861
