id: AA321C2AB
title: A Brief Practice for Paying Homage and Making Offerings to the Buddha together
  with his retinue of Arhats
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 02:21:34.817669
  last_modified_at: 2022-03-01 02:21:34.817677
